# run: conda env create --file environment-2.yml
name: qml2
channels:
  - conda-forge
dependencies:
  - python=2.7
  - matplotlib
  - scikit-learn
  - pandas
  - seaborn
  - tqdm
  - pip:
    - cython
    - tensorflow
